
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ymtshop

test: 12345

#eureka:
#  client:
#  serviceUrl:
#  defaultZone: http://localhost:8761/eureka/

#ymtshop:
#  amqp:
#  rabbit:
#  address: localhost:5672
#  username: guest
#  password: guest
#  vhost: /
#  exchange: Ymtshop-exchange
#  queue: Ymtshop-product-queue