
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom

server:
  port: 8081

eureka:
  client:
  serviceUrl:
  defaultZone: http://localhost:8761/eureka/


axon:
  axonserver:
    enabled: false
ymtshop:
  amqp:
    rabbit:
      address: localhost:5672
      username: guest
      password: guest
      vhost: /
      exchange: Ymtshop-exchange
      queue: Ymtshop-product-queue
      routingKey: product-module