server:
    port: 8084
eureka:
  client:
  serviceUrl:
  defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

axon:
  axonserver:
    enabled: false
ymtshop:
  amqp:
    rabbit:
      address: localhost:5672
      username: guest
      password: guest
      vhost: /
      exchange: Ymtshop-exchange
      queue: Ymtshop-core-queue
      routingKey: core-module
logging:
  level:
    org:
      springframework:
        amqp: DEBUG